.\" Manpage for bomi.
.\" Contact breed808@breed808.com to correct errors or typos.
.TH BOMI 1 "10/10/14" "\ \&" "\ \&"
.SH "NAME"
bomi \- Play multimedia files
.SH "SYNOPSIS"
.sp
\fIbomi\fR [options] [files\&...]
.SH "DESCRIPTION"
.sp
bomi is a powerful mediaplayer capable of playing a wide range of audio and video formatsi\&. bomi can play from
sources such as local files, remote URLs, DVDs/CDs and Blu-Ray discs\&.
.SH "OPTIONS"
.PP
\fB\-\-action\fR <id>
.RS 4
Execute <id> action or open <id> menu\&.
.RE
.PP
\fB\-\-debug\fR
.RS 4
Enables debugging output\&.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Display help message and exit\&.
.RE
.PP
\fB\-\-log\-level\fR <lv>
.RS 4
Set logging verbosity\&. <lv> may be one of the following: fatal, error, warn, info, debug, trace\&.
.RE
.PP
\fB\-\-open\fR <file>
.RS 4
Open <file> with bomi. <file> may be a local file/path, remote url, or CD/DVD/Blu-Ray\&.
.RE
.PP
\fB\-\-opengl\-debug\fR
.RS 4
Enables OpenGL debugging\&.
.RE
.PP
\fB\-v, \-\-version\fR
.RS 4
Print program version info and exit\&.
.RE
.PP
\fB\-\-wake\fR
.RS 4
Bring application window to front\&.
.RE
.SH "AUTHORS"
.sp
Current maintainers:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Xylosper <darklin20@gmail\&.com> - Project developer
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Ben Reedy <breed808@breed808\&.com> - Manpage maintainer
.RE
