#!/bin/bash

args="--disable-encoding --disable-libguess --disable-terminfo --disable-termcap --disable-termios --enable-iconv \
  --disable-lirc --disable-lircc --disable-joystick --disable-vm --disable-xf86keysym --disable-radio \
  --disable-radio-capture --disable-radio-v4l2 --disable-tv --disable-tv-v4l2 --disable-pvr \
  --disable-smb --enable-libquvi4 --disable-libquvi9 --disable-lcms2 --disable-vcd --disable-bluray --enable-dvdread \
  --disable-enca --enable-pthreads  \
  --disable-rpath --disable-libpostproc --disable-libavdevice --disable-libavfilter --disable-vf-lavfi --disable-af-lavfi --disable-mng \
  --disable-jpeg --enable-libcdio --disable-ladspa --disable-libbs2b --enable-mpg123 --disable-libavresample \
  --disable-gl --disable-caca --disable-direct3d --disable-sdl --disable-sdl2 --disable-xv --disable-vdpau \
  --disable-vm --disable-xinerama --disable-x11 --disable-wayland --disable-xss --disable-corevideo --disable-cocoa \
  --disable-ossaudio --disable-rsound --enable-portaudio --enable-openal --disable-dsound --disable-wasapi --enable-select \
  --disable-gettext --disable-cross-compile --disable-shm"

libs="-ldvdread -lbz2 -lcdio_cdda -lcdio_paranoia -lcdio -lmpg123 -lquvi -lass" # -lfontconfig -lexpat -lfreetype -lharfbuzz -lenca -lm"

# --enable-libass --enable-libass-osd

kern=`uname -s`
if test $kern = "Darwin"
then
  echo "Build for OS X"
  args="$args --enable-coreaudio --disable-alsa --disable-pulse --disable-jack --disable-vaapi --enable-vda"
  libs="$libs -framework VideoDecodeAcceleration -framework CoreVideo -framework CoreFoundation -framework Cocoa"
  PKG_CONFIG_PATH="/usr/X11/lib/pkgconfig:${PKG_CONFIG_PATH}"
elif test $kern = "Linux"
then
  echo "Build for Linux"
  args="$args --disable-coreaudio --enable-alsa --enable-pulse --enable-jack --enable-vaapi --disable-vda"
  libs="$libs -lasound -lva"
else
  echo "Not supported!"
  exit
fi

export PKG_CONFIG_PATH="../../build/lib/pkgconfig:${PKG_CONFIG_PATH}"
cd src/mpv && make distclean;  ./configure $args --extra-libs="$libs"
make -j 6

allobjs=`find . -name '*.o'`
objs=""
for obj in $allobjs; do
	if [[ $obj =~ ^.*(vo_null|af_dummy|vaapi|vdpau|vda).o$ ]]; then
		continue
	fi
	objs+=" $obj"
done

ar rcsv ../../build/lib/libcmplayer_mpv.a $objs
