#!/bin/sh

args="--prefix=../../build --enable-gpl --enable-runtime-cpudetect --disable-debug \
  --enable-pthreads --disable-shared --enable-static \
  --disable-devices --enable-vaapi --enable-vda --disable-avconv \
  --disable-avplay --disable-avserver --disable-avprobe"

kern=`uname -s`
if test $kern = "Darwin"
then
  echo "Build for OS X"
  args="$args --enable-vda --disable-vaapi"
#  cd src/libav && make distclean; ./configure $args && make -j 6 && make install
  cd build/lib && \
  	ar x libavutil.a && ar x libavcodec.a && ar x libavformat.a && ar x libswscale.a && \
  	ar rcsv libcmplayer_av.a *.o && rm *.o
elif test $kern = "Linux"
then
  echo "Build for Linux"
  args="$args --disable-vda --enable-vaapi"
  cd src/libav && make distclean; ./configure $args && make -j 6 && make install
  cd build/lib && ar qTsv libcmplayer_av.a libavutil.a libavcodec.a libavformat.a libswscale.a
fi

