#!/bin/sh

args="--prefix=../../build --enable-gpl --disable-debug \
  --disable-shared --enable-static --enable-runtime-cpudetect \
  --disable-doc --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-ffserver \
  --disable-avdevice --disable-avfilter --disable-swresample --enable-avresample --enable-pthreads \
  --disable-dxva2 --disable-vdpau --disable-postproc \
  --disable-encoders --disable-muxers --disable-devices --disable-filters"
  
kern=`uname -s`
if test $kern = "Darwin"
then
  echo "Build for OS X"
  args="$args --enable-vda --disable-vaapi"
  cd src/ffmpeg && make distclean; ./configure $args && make -j 6 && make install
elif test $kern = "Linux"
then
  echo "Build for Linux"
  args="$args --disable-vda --enable-vaapi"
  cd src/ffmpeg && make distclean; ./configure $args && make -j 6 && make install && \
  cd ../../build/lib && ar qTsv libcmplayer_av.a libavutil.a libavcodec.a libavformat.a libswscale.a libavresample.a
fi

