#!/bin/sh

args="--prefix=../../build --enable-gpl --disable-debug \
  --disable-shared --enable-static --enable-runtime-cpudetect \
  --disable-doc --disable-avconv --disable-avplay --disable-avprobe --disable-avserver \
  --disable-avdevice --disable-avfilter --disable-avresample --enable-pthreads \
  --disable-dxva2 --disable-vdpau --enable-vda --enable-vaapi \
  --disable-encoders --disable-muxers --disable-devices --disable-filters"
  
kern=`uname -s`
if test $kern = "Darwin"
then
  echo "Build for OS X"
  args="$args --enable-vda --disable-vaapi"
  cd src/libav && make distclean; ./configure $args && make -j 6 && make install
elif test $kern = "Linux"
then
  echo "Build for Linux"
  args="$args --disable-vda --enable-vaapi"
  cd src/libav && make distclean; ./configure $args && make -j 6 && make install && \
  cd ../../build/lib && ar qTsv libcmplayer_av.a libavutil.a libavcodec.a libavformat.a libswscale.a
fi

