#!/bin/sh

args="--prefix=`pwd`/build --enable-gpl --disable-debug --disable-shared --enable-static \
  --enable-runtime-cpudetect --disable-doc --disable-programs --enable-gnutls \
  --disable-avdevice --enable-avfilter --enable-swresample --disable-avresample --enable-pthreads \
  --disable-devices --enable-filters --enable-libx264 --enable-libvorbis --enable-libvpx --enable-libmp3lame"

kern=`uname -s`
procs=$(nproc)

if test $kern = "Darwin"; then
  echo "Build for OS X"
  args="$args --enable-vda --disable-vaapi --disable-vdpau"
  procs=5
elif test $kern = "Linux"; then
  echo "Build for Linux"
  args="$args --disable-vda --enable-vaapi --enable-vdpau"
else
  echo "Build for Windows"
  args="$args --enable-dxva2 --target-os=mingw32"
  export PKG_CONFIG_PATH="/mingw64/lib/pkgconfig:${PKG_CONFIG_PATH}"
  export PATH="/mingw64/bin:${PATH}"
fi

cd src/ffmpeg* && make distclean; ./configure $args && make -j $procs && make install
