#!/bin/sh

args="--enable-runtime-cpudetection \
  --disable-termcap --disable-termios --disable-iconv --disable-langinfo \
  --disable-lirc --disable-lircc --disable-joystick --disable-apple-remote --disable-apple-ir \
  --disable-vm --disable-xf86keysym --disable-radio --disable-radio-capture --disable-radio-v4l2 \
  --disable-radio-bsdbt848 --disable-tv --disable-tv-v4l1 --disable-tv-v4l2 --disable-tv-bsdbt848 \
  --disable-pvr --disable-rtc --enable-networking --disable-winsock2_h --disable-smb \
  --disable-vcd --disable-bluray --enable-dvdnav --enable-dvdread --disable-dvdread-internal \
  --disable-libdvdcss-internal --enable-cddb --disable-unrarexec --disable-sortsub --disable-enca \
  --disable-macosx-finder --disable-macosx-bundle --enable-inet6 --enable-gethostbyname2 --enable-ftp \
  --disable-vstream --enable-pthreads --disable-w32threads --disable-libass --disable-rpath \
  --disable-libpostproc --disable-gif --disable-png --disable-mng --disable-jpeg --enable-libcdio \
  --disable-win32dll --disable-qtx --disable-xanim --disable-real --enable-xvid --disable-libnut \
  --enable-libav --enable-libvorbis --disable-tremor --disable-speex --enable-theora --enable-faad \
  --disable-ladspa --disable-libbs2b --enable-libdv --disable-mpg123 --enable-mad --disable-xmms \
  --enable-libdca --enable-liba52 --disable-musepack --disable-gl --disable-corevideo --disable-cocoa \
  --disable-x11 --disable-sdl --disable-caca --disable-direct3d --disable-directx --disable-v4l2 \
  --disable-dvb --disable-xv --disable-vdpau --disable-vm --disable-xinerama --disable-xshape \
  --disable-xss --disable-directfb --disable-tga --disable-pnm --disable-md5sum --disable-yuv4mpeg \
  --disable-sharedbuffer --enable-openal --disable-ossaudio --disable-rsound --disable-pulse \
  --disable-portaudio --disable-jack --disable-select --disable-translation --disable-static"
cflags="-I../../build/include"
objs="command.o m_property.o mixer.o mp_fifo.o parser-mpcmd.o \
  screenshot.o input/input.o libao2/ao_null.o libao2/ao_pcm.o \
  libao2/audio_out.o libvo/aspect.o libvo/csputils.o libvo/geometry.o libvo/old_vo_wrapper.o \
  libvo/video_out.o libvo/vo_null.o libvo/vo_png.o libao2/ao_openal.o \
  asxparser.o av_log.o av_opts.o bstr.o codec-cfg.o cpudetect.o defaultopts.o fmt-conversion.o m_config.o \
  m_option.o m_struct.o mpcommon.o parser-cfg.o path.o playtree.o playtreeparser.o \
  subopt-helper.o talloc.o libaf/af.o libaf/af_center.o libaf/af_channels.o libaf/af_comp.o \
  libaf/af_delay.o libaf/af_dummy.o libaf/af_equalizer.o libaf/af_extrastereo.o \
  libaf/af_format.o libaf/af_gate.o libaf/af_hrtf.o libaf/af_karaoke.o libaf/af_lavcac3enc.o \
  libaf/af_lavcresample.o libaf/af_pan.o libaf/af_resample.o libaf/af_scaletempo.o \
  libaf/af_sinesuppress.o libaf/af_stats.o libaf/af_sub.o libaf/af_surround.o libaf/af_sweep.o \
  libaf/af_tools.o libaf/af_volnorm.o libaf/af_volume.o libaf/filter.o libaf/format.o \
  libaf/reorder_ch.o libaf/window.o libmpcodecs/ad.o libmpcodecs/ad_alaw.o \
  libmpcodecs/ad_dk3adpcm.o libmpcodecs/ad_dvdpcm.o libmpcodecs/ad_ffmpeg.o \
  libmpcodecs/ad_hwac3.o libmpcodecs/ad_hwmpa.o libmpcodecs/ad_imaadpcm.o \
  libmpcodecs/ad_msadpcm.o libmpcodecs/ad_pcm.o libmpcodecs/dec_audio.o \
  libmpcodecs/dec_teletext.o libmpcodecs/dec_video.o libmpcodecs/img_format.o \
  libmpcodecs/mp_image.o libmpcodecs/pullup.o libmpcodecs/vd.o \
  libmpcodecs/vd_hmblck.o libmpcodecs/vd_lzo.o libmpcodecs/vd_mpegpes.o libmpcodecs/vd_mtga.o \
  libmpcodecs/vd_null.o libmpcodecs/vd_raw.o libmpcodecs/vd_sgi.o libmpcodecs/vf.o \
  libmpcodecs/vf_1bpp.o libmpcodecs/vf_2xsai.o libmpcodecs/vf_blackframe.o \
  libmpcodecs/vf_boxblur.o libmpcodecs/vf_crop.o libmpcodecs/vf_cropdetect.o \
  libmpcodecs/vf_decimate.o libmpcodecs/vf_delogo.o libmpcodecs/vf_denoise3d.o \
  libmpcodecs/vf_detc.o libmpcodecs/vf_dint.o libmpcodecs/vf_divtc.o \
  libmpcodecs/vf_down3dright.o libmpcodecs/vf_dsize.o libmpcodecs/vf_dvbscale.o \
  libmpcodecs/vf_eq.o libmpcodecs/vf_eq2.o libmpcodecs/vf_expand.o libmpcodecs/vf_field.o \
  libmpcodecs/vf_fil.o libmpcodecs/vf_filmdint.o libmpcodecs/vf_fixpts.o libmpcodecs/vf_flip.o \
  libmpcodecs/vf_format.o libmpcodecs/vf_framestep.o libmpcodecs/vf_fspp.o libmpcodecs/vf_geq.o \
  libmpcodecs/vf_gradfun.o libmpcodecs/vf_halfpack.o libmpcodecs/vf_harddup.o \
  libmpcodecs/vf_hqdn3d.o libmpcodecs/vf_hue.o libmpcodecs/vf_il.o libmpcodecs/vf_ilpack.o \
  libmpcodecs/vf_ivtc.o libmpcodecs/vf_kerndeint.o libmpcodecs/vf_lavc.o \
  libmpcodecs/vf_lavcdeint.o libmpcodecs/vf_mirror.o libmpcodecs/vf_noformat.o \
  libmpcodecs/vf_noise.o libmpcodecs/vf_ow.o libmpcodecs/vf_palette.o \
  libmpcodecs/vf_perspective.o libmpcodecs/vf_phase.o libmpcodecs/vf_pp7.o \
  libmpcodecs/vf_pullup.o libmpcodecs/vf_qp.o libmpcodecs/vf_rectangle.o \
  libmpcodecs/vf_remove_logo.o libmpcodecs/vf_rgbtest.o libmpcodecs/vf_rotate.o \
  libmpcodecs/vf_sab.o libmpcodecs/vf_scale.o libmpcodecs/vf_screenshot.o \
  libmpcodecs/vf_smartblur.o libmpcodecs/vf_softpulldown.o libmpcodecs/vf_stereo3d.o \
  libmpcodecs/vf_softskip.o libmpcodecs/vf_swapuv.o libmpcodecs/vf_telecine.o \
  libmpcodecs/vf_test.o libmpcodecs/vf_tfields.o libmpcodecs/vf_tile.o \
  libmpcodecs/vf_tinterlace.o libmpcodecs/vf_unsharp.o libmpcodecs/vf_uspp.o \
  libmpcodecs/vf_vo.o libmpcodecs/vf_yadif.o libmpcodecs/vf_yuvcsp.o libmpcodecs/vf_yvu9.o \
  libmpdemux/aac_hdr.o libmpdemux/asfheader.o libmpdemux/aviheader.o libmpdemux/aviprint.o \
  libmpdemux/demuxer.o libmpdemux/demux_aac.o libmpdemux/demux_asf.o libmpdemux/demux_audio.o \
  libmpdemux/demux_avi.o libmpdemux/demux_demuxers.o libmpdemux/demux_edl.o \
  libmpdemux/demux_film.o libmpdemux/demux_fli.o libmpdemux/demux_lavf.o \
  libmpdemux/demux_lmlm4.o libmpdemux/demux_mf.o libmpdemux/demux_mkv.o libmpdemux/demux_mov.o \
  libmpdemux/demux_mpg.o libmpdemux/demux_nsv.o libmpdemux/demux_pva.o \
  libmpdemux/demux_rawaudio.o libmpdemux/demux_rawvideo.o libmpdemux/demux_realaud.o \
  libmpdemux/demux_real.o libmpdemux/demux_roq.o libmpdemux/demux_smjpeg.o \
  libmpdemux/demux_ts.o libmpdemux/demux_ty.o libmpdemux/demux_viv.o libmpdemux/demux_vqf.o \
  libmpdemux/demux_y4m.o libmpdemux/ebml.o libmpdemux/extension.o libmpdemux/mf.o \
  libmpdemux/mp3_hdr.o libmpdemux/mp_taglists.o libmpdemux/mpeg_hdr.o \
  libmpdemux/mpeg_packetizer.o libmpdemux/parse_es.o libmpdemux/parse_mp4.o \
  libmpdemux/video.o libmpdemux/yuv4mpeg.o libmpdemux/yuv4mpeg_ratio.o libvo/osd.o \
  osdep/numcores.o osdep/io.o osdep/getch2.o \
  stream/stream.o stream/stream_cue.o stream/stream_ffmpeg.o stream/stream_file.o \
  stream/stream_mf.o stream/stream_null.o stream/url.o sub/dec_sub.o \
  sub/find_sub.o sub/find_subfiles.o sub/spudec.o sub/sub.o sub/sub_cc.o sub/subassconvert.o \
  sub/subreader.o sub/vobsub.o sub/osd_dummy.o sub/sd_lavc.o timeline/tl_edl.o timeline/tl_matroska.o \
  stream/stream_cdda.o stream/cdinfo.o stream/stream_cddb.o stream/stream_dvdnav.o \
  stream/stream_dvd.o stream/stream_dvd_common.o libmpcodecs/ad_faad.o libvo/aclib.o \
  stream/stream_ftp.o libmpcodecs/vf_bmovl.o libaf/af_export.o osdep/mmap_anon.o \
  libmpcodecs/ad_liba52.o libmpcodecs/ad_libdca.o libmpcodecs/ad_libdv.o libmpcodecs/vd_libdv.o \
  libmpdemux/demux_rawdv.o libmpcodecs/ad_libmad.o libmpcodecs/vd_theora.o \
  osdep/shmem.o stream/stream_netstream.o stream/asf_mmst_streaming.o stream/asf_streaming.o stream/cookies.o \
  stream/http.o stream/network.o stream/pnm.o stream/rtp.o stream/udp.o stream/tcp.o \
  stream/stream_rtp.o stream/stream_udp.o stream/cache2.o stream/quvi.o stream/stream.o \
  libmpcodecs/ad_libvorbis.o libmpdemux/demux_ogg.o libmpcodecs/vd_xvid4.o"

libs="-lz -lbz2 -lxvidcore -lvorbis -logg -ltheora -la52 -ldca -lcdio_paranoia -lcdio_cdda -lcdio"

kern=`uname -s`
if test $kern = "Darwin"
then
  echo "Build for OS X"
  args="--cc=gcc-4.2 $args --enable-coreaudio --disable-alsa"
  libs="../../build/lib/libavformat.a ../../build/lib/libavcodec.a \
  	../../build/lib/libavutil.a ../../build/lib/libswscale.a $libs \
  	-framework OpenAL -framework VideoDecodeAcceleration -framework CoreVideo -framework CoreFoundation -framework Cocoa"
  objs="$objs libao2/ao_coreaudio.o osdep/timer-darwin.o"
elif test $kern = "Linux"
then
  echo "Build for Linux"
  args="--cc=gcc $args --disable-coreaudio --enable-alsa"
  libs="-L../../build/lib -lcmplayer_av $libs -lopenal -lasound -lva"
  objs="$objs libao2/ao_alsa.o osdep/timer-linux.o"
else
  echo "Not supported!"
  exit
fi

cd src/mplayer2 && make distclean; ./configure $args --extra-cflags="$cflags" --extra-libs="$libs" \
  && make -j 6 && ar rcsv ../../build/lib/libcmplayer_mplayer2.a $objs
