#!/bin/sh

dir=build/bomi-win-$(date +%Y%m%d%H%M%S)

#make skins
#make imports
#make translations

install -d $dir
cp build/bomi.exe $dir
cd $dir

cp -r ../skins .
cp -r ../imports .
cp -r ../translations .

install -d QtQuick
cp -r /mingw64/qt5-static/share/qt5/qml/QtQuick/{Controls,Layouts,Window.2} QtQuick/
cp -r /mingw64/qt5-static/share/qt5/qml/QtQuick.2 .
cp /mingw64/qt5-static/share/qt5/translations/qt_{ar,ca,cs,da,de,es,fa,fi,fr,gl,he}.qm translations/

find QtQuick{,.2} -name 'lib*.a' | xargs rm

