#! /bin/bash

git clone --depth=1 git://github.com/xylosper/bomi bomi
git clone --depth=1 git://github.com/xylosper/mpv bomi/src/mpv
cd bomi/src/mpv && python ./bootstrap.py && cd ../../..

rm -rf `find ./bomi -name '.git*'`

ver=`head -1 bomi/CHANGES.txt`
mv bomi bomi-$ver
tar cvfz bomi-$ver-source.tar.gz bomi-$ver
sed -i "s/^md5sums=(.*$/md5sums=('`md5sum bomi-$ver-source.tar.gz | sed "s/\s*bomi-.*$//"`')/" PKGBUILD 
